### ISSUE TITLE
fullscreen option please

### ISSUE THREAD

**Issue by MadameMalady** [mlm-games/asteroids-revenge#4]
Hi! I like your asteroids game, it works well on my linux phones, I was wondering if it's possible to add a 'fullscreen' option to the settings? 

Either way, thanks for making this game!

**Comment by mlm-games** [comment]
Will add an option to ignore ratios probably in the next release (along with x64_86 android versions). It should cause the game to cover the whole screen

Anyways, Glad you liked my game :)

**Comment by mlm-games** [comment]
Hey, I added the fullscreen toggle in settings, Can you confirm if the fullscreen button works properly for your mobile?

**Comment by MadameMalady** [comment]
sure, will test the next update as soon as I see it ^~^

**Comment by MadameMalady** [comment]
Tested it a few minutes ago, screenshot attatched; looks pretty good, thank you!
![Screenshot from 2024-09-22 17-27-07](https://github.com/user-attachments/assets/58d4cd03-e07b-433e-9434-71e426e90fad)

**Comment by mlm-games** [comment]
Nice! Thanks for testing
